
SELECT S.FIRST_NAME||' '||S.LAST_NAME STUDENT_NAME
FROM STUDENTS S
WHERE S.STUDENT_ID = (SELECT S2.STUDENT_ID
                    FROM STUDENTS S2, STU_USERS SU
                    WHERE S2.STUDENT_ID = SU.STUDENT_ID
                    AND UPPER(SU.USER_NAME) = UPPER(:APP_USER))