
SELECT C.CLASS_NAME, SEC.SECTION_NAME, A.ROLL_NO, AD.YEAR_NAME, A.ADMISSION_DATE
   	FROM STUDENTS S, CLASS C,  ADMISSION A, SECTIONS SEC, ACADEMIC_YEARS AD
	WHERE S.student_id = A.student_id
    AND C.CLASS_ID = A.CLASS_ID
    AND SEC.SECTION_ID = A.SECTION_ID
    AND A.ACADEMIC_YEAR_ID = AD.ACADEMIC_YEAR_ID
    AND S.STUDENT_ID = (select STUDENT_ID
                    FROM STU_USERS
                    WHERE UPPER(USER_NAME) = UPPER(:APP_USER))