
select S.STUDENT_ID,
S.FIRST_NAME||' '||S.LAST_NAME Full_name,
S.GENDER,
S.RELIGION,
S.DATE_OF_BIRTH,
S.BLOOD_GROUP,
S.EMAIL,
S.PHONE_NO,
S.PRESENT_ADDRESS,
S.PERMANENT_ADDRESS,
sys.dbms_lob.getlength(S.PICTURE) PICTURE,
S.MIMETYPE,
S.FILENAME,
S.IMG_LAST_UPDATE,
S.STATUS
from STUDENTS S
where S.STUDENT_ID = (select STUDENT_ID
                    FROM STU_USERS
                    WHERE UPPER(USER_NAME) = UPPER(:APP_USER))